-- =============================================================================
-- EwpBffStateDb - server-side sessions and Data Protection keys of the .NET BFFs
-- =============================================================================
-- Create the database once (as postgres):  CREATE DATABASE "EwpBffStateDb";
-- Run db\Apply-EwpServiceDbUsers.ps1 (creates the BFF users), then, while connected to
-- EwpBffStateDb (it drops and recreates the schemas - everybody is signed out):
--   psql -h localhost -U postgres -d EwpBffStateDb -v ON_ERROR_STOP=1 -f db\EwpBffStateDb.sql
--
-- One schema per BFF, used only by that BFF's own database user (least privilege): a BFF
-- can neither read nor change another BFF's sessions or keys.
--   shell_bff               ewp_shell            (Shell BFF)
--   customer_onboarding_bff ewp_co_bff           (Customer Onboarding BFF)
--   compliance_bff          ewp_compliance_bff   (Compliance BFF)
--   accounts_bff            ewp_accounts_bff     (Accounts BFF)
--   payments_bff            ewp_payments_bff     (Payments BFF)
--
-- "UserSessions" is Duende BFF's server-side session table, exactly as its EF store maps it
-- (PascalCase names are Duende's). data_protection_keys holds the BFF's key ring, which
-- encrypts its session and anti-forgery cookies (on Windows also encrypted with DPAPI).
-- =============================================================================

DO $$
DECLARE
    b RECORD;
BEGIN
    FOR b IN SELECT * FROM (VALUES
        ('shell_bff',               'ewp_shell'),
        ('customer_onboarding_bff', 'ewp_co_bff'),
        ('compliance_bff',          'ewp_compliance_bff'),
        ('accounts_bff',            'ewp_accounts_bff'),
        ('payments_bff',            'ewp_payments_bff')
    ) AS t(schema_name, role_name)
    LOOP
        EXECUTE format('DROP SCHEMA IF EXISTS %I CASCADE', b.schema_name);
        EXECUTE format('CREATE SCHEMA %I', b.schema_name);

        -- Duende BFF server-side sessions (Duende.BFF.EntityFramework 4.3).
        EXECUTE format($sql$
            CREATE TABLE %1$I."UserSessions" (
                "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
                "SubjectId" character varying(200) NOT NULL,
                "SessionId" text,
                "Created" timestamp with time zone NOT NULL,
                "Renewed" timestamp with time zone NOT NULL,
                "Expires" timestamp with time zone,
                "Ticket" text NOT NULL,
                "Key" character varying(200) NOT NULL,
                "PartitionKey" character varying(200),
                CONSTRAINT "PK_UserSessions" PRIMARY KEY ("Id")
            )$sql$, b.schema_name);
        EXECUTE format('CREATE INDEX "IX_UserSessions_Expires" ON %I."UserSessions" ("Expires")', b.schema_name);
        EXECUTE format('CREATE UNIQUE INDEX "IX_UserSessions_PartitionKey_Key" ON %I."UserSessions" ("PartitionKey", "Key")', b.schema_name);
        EXECUTE format('CREATE UNIQUE INDEX "IX_UserSessions_PartitionKey_SessionId" ON %I."UserSessions" ("PartitionKey", "SessionId")', b.schema_name);
        EXECUTE format('CREATE UNIQUE INDEX "IX_UserSessions_PartitionKey_SubjectId_SessionId" ON %I."UserSessions" ("PartitionKey", "SubjectId", "SessionId")', b.schema_name);

        -- ASP.NET Core Data Protection key ring.
        EXECUTE format($sql$
            CREATE TABLE %1$I.data_protection_keys (
                id integer GENERATED BY DEFAULT AS IDENTITY,
                friendly_name text,
                xml text,
                CONSTRAINT "PK_data_protection_keys" PRIMARY KEY (id)
            )$sql$, b.schema_name);

        -- Only the BFF's own user, and only data access (no DDL).
        IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = b.role_name) THEN
            EXECUTE format('GRANT USAGE ON SCHEMA %I TO %I', b.schema_name, b.role_name);
            EXECUTE format('GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA %I TO %I', b.schema_name, b.role_name);
            EXECUTE format('GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA %I TO %I', b.schema_name, b.role_name);
        ELSE
            RAISE WARNING 'Role % does not exist yet: run db\Apply-EwpServiceDbUsers.ps1, then this script again.', b.role_name;
        END IF;
    END LOOP;
END $$;

SELECT n.nspname AS schema, c.relname AS "table"
FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
WHERE c.relkind = 'r' AND n.nspname LIKE '%\_bff'
ORDER BY 1, 2;