-- =============================================================================
-- EwpBffStateDb - server-side sessions of every BFF (and the .NET BFFs' Data Protection keys)
-- =============================================================================
-- Create the database once (as postgres):  CREATE DATABASE "EwpBffStateDb";
-- Run ps\database\Apply-EwpServiceDbUsers.ps1 (creates the BFF users), then, while connected to
-- EwpBffStateDb (it drops and recreates the schemas - everybody is signed out):
--   psql -h localhost -U postgres -d EwpBffStateDb -v ON_ERROR_STOP=1 -f db\EwpBffStateDb.sql
--
-- One schema per BFF, used only by that BFF's own database user (least privilege): a BFF
-- can neither read nor change another BFF's sessions or keys.
--   shell_bff               ewp_shell            (Shell BFF)
--   customer_onboarding_bff ewp_co_bff           (Customer Onboarding BFF)
--   compliance_bff          ewp_compliance_bff   (Compliance BFF)
--   accounts_bff            ewp_accounts_bff     (Accounts BFF)
--   payments_bff            ewp_payments_bff     (Payments BFF)
--   kyc_bff                 ewp_kyc_bff          (Customer KYC BFF - NestJS; its own table, below)
--   audit_bff               ewp_audit_web        (Audit web - the Next.js light BFF; its own table, below)
--
-- "UserSessions" is Duende BFF's server-side session table, exactly as its EF store maps it
-- (PascalCase names are Duende's). data_protection_keys holds the BFF's key ring, which
-- encrypts its session and anti-forgery cookies (on Windows also encrypted with DPAPI).
-- =============================================================================

DO $$
DECLARE
    b RECORD;
BEGIN
    FOR b IN SELECT * FROM (VALUES
        ('shell_bff',               'ewp_shell'),
        ('customer_onboarding_bff', 'ewp_co_bff'),
        ('compliance_bff',          'ewp_compliance_bff'),
        ('accounts_bff',            'ewp_accounts_bff'),
        ('payments_bff',            'ewp_payments_bff')
    ) AS t(schema_name, role_name)
    LOOP
        EXECUTE format('DROP SCHEMA IF EXISTS %I CASCADE', b.schema_name);
        EXECUTE format('CREATE SCHEMA %I', b.schema_name);

        -- Duende BFF server-side sessions (Duende.BFF.EntityFramework 4.3).
        EXECUTE format($sql$
            CREATE TABLE %1$I."UserSessions" (
                "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
                "SubjectId" character varying(200) NOT NULL,
                "SessionId" text,
                "Created" timestamp with time zone NOT NULL,
                "Renewed" timestamp with time zone NOT NULL,
                "Expires" timestamp with time zone,
                "Ticket" text NOT NULL,
                "Key" character varying(200) NOT NULL,
                "PartitionKey" character varying(200),
                CONSTRAINT "PK_UserSessions" PRIMARY KEY ("Id")
            )$sql$, b.schema_name);
        EXECUTE format('CREATE INDEX "IX_UserSessions_Expires" ON %I."UserSessions" ("Expires")', b.schema_name);
        EXECUTE format('CREATE UNIQUE INDEX "IX_UserSessions_PartitionKey_Key" ON %I."UserSessions" ("PartitionKey", "Key")', b.schema_name);
        EXECUTE format('CREATE UNIQUE INDEX "IX_UserSessions_PartitionKey_SessionId" ON %I."UserSessions" ("PartitionKey", "SessionId")', b.schema_name);
        EXECUTE format('CREATE UNIQUE INDEX "IX_UserSessions_PartitionKey_SubjectId_SessionId" ON %I."UserSessions" ("PartitionKey", "SubjectId", "SessionId")', b.schema_name);

        -- ASP.NET Core Data Protection key ring.
        EXECUTE format($sql$
            CREATE TABLE %1$I.data_protection_keys (
                id integer GENERATED BY DEFAULT AS IDENTITY,
                friendly_name text,
                xml text,
                CONSTRAINT "PK_data_protection_keys" PRIMARY KEY (id)
            )$sql$, b.schema_name);

        -- Only the BFF's own user, and only data access (no DDL).
        IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = b.role_name) THEN
            EXECUTE format('GRANT USAGE ON SCHEMA %I TO %I', b.schema_name, b.role_name);
            EXECUTE format('GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA %I TO %I', b.schema_name, b.role_name);
            EXECUTE format('GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA %I TO %I', b.schema_name, b.role_name);
        ELSE
            RAISE WARNING 'Role % does not exist yet: run ps\database\Apply-EwpServiceDbUsers.ps1, then this script again.', b.role_name;
        END IF;
    END LOOP;
END $$;

-- -----------------------------------------------------------------------------
-- audit_bff: the Next.js light BFF of the Audit context (not Duende). The key is the SHA-256
-- of the session cookie, never the cookie itself; data holds the person's tokens encrypted
-- with AES-256-GCM (the key, AUDIT_WEB_SESSION_KEY, is not in the database). So a database
-- reader can neither hijack nor read a session.
-- -----------------------------------------------------------------------------
DROP SCHEMA IF EXISTS audit_bff CASCADE;
CREATE SCHEMA audit_bff;

CREATE TABLE audit_bff.sessions (
    session_hash CHAR(64)     NOT NULL,
    subject_id   VARCHAR(200) NOT NULL,
    sid          VARCHAR(200) NULL,       -- the IDP session: front- and back-channel logout end it
    data         TEXT         NOT NULL,   -- AES-256-GCM: iv | tag | ciphertext, base64
    created_at   TIMESTAMPTZ  NOT NULL,
    renewed_at   TIMESTAMPTZ  NOT NULL,
    expires_at   TIMESTAMPTZ  NOT NULL,   -- sliding, 30 minutes
    CONSTRAINT pk_audit_bff_sessions PRIMARY KEY (session_hash)
);
CREATE INDEX ix_audit_bff_sessions_sid ON audit_bff.sessions (sid);
CREATE INDEX ix_audit_bff_sessions_subject ON audit_bff.sessions (subject_id);
CREATE INDEX ix_audit_bff_sessions_expires ON audit_bff.sessions (expires_at);

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'ewp_audit_web') THEN
        GRANT USAGE ON SCHEMA audit_bff TO ewp_audit_web;
        GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA audit_bff TO ewp_audit_web;
    ELSE
        RAISE WARNING 'Role ewp_audit_web does not exist yet: run ps\database\Apply-EwpServiceDbUsers.ps1, then this script again.';
    END IF;
END $$;

-- -----------------------------------------------------------------------------
-- kyc_bff: the Customer KYC BFF (NestJS, express-session). The key is the SHA-256 of the session
-- ID, never the ID itself (that is only in the signed cookie); data is the whole session - the
-- officer's tokens included - encrypted with AES-256-GCM (the key, KYC_BFF_SESSION_KEY, is not in
-- the database). subject_id and sid stay readable so back-channel logout can find the rows.
-- -----------------------------------------------------------------------------
DROP SCHEMA IF EXISTS kyc_bff CASCADE;
CREATE SCHEMA kyc_bff;

CREATE TABLE kyc_bff.sessions (
    session_hash CHAR(64)     NOT NULL,
    subject_id   VARCHAR(200) NULL,       -- null until sign-in completes (the pending sign-in has a session too)
    sid          VARCHAR(200) NULL,       -- the IDP session: back-channel logout ends it
    data         TEXT         NOT NULL,   -- AES-256-GCM: iv | tag | ciphertext, base64
    created_at   TIMESTAMPTZ  NOT NULL,
    renewed_at   TIMESTAMPTZ  NOT NULL,
    expires_at   TIMESTAMPTZ  NOT NULL,   -- sliding, 30 minutes
    CONSTRAINT pk_kyc_bff_sessions PRIMARY KEY (session_hash)
);
CREATE INDEX ix_kyc_bff_sessions_sid ON kyc_bff.sessions (sid);
CREATE INDEX ix_kyc_bff_sessions_subject ON kyc_bff.sessions (subject_id);
CREATE INDEX ix_kyc_bff_sessions_expires ON kyc_bff.sessions (expires_at);

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'ewp_kyc_bff') THEN
        GRANT USAGE ON SCHEMA kyc_bff TO ewp_kyc_bff;
        GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA kyc_bff TO ewp_kyc_bff;
    ELSE
        RAISE WARNING 'Role ewp_kyc_bff does not exist yet: run ps\database\Apply-EwpServiceDbUsers.ps1, then this script again.';
    END IF;
END $$;

SELECT n.nspname AS schema, c.relname AS "table"
FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
WHERE c.relkind = 'r' AND n.nspname LIKE '%\_bff'
ORDER BY 1, 2;