-- ============================================================================
-- EnterpriseWebPlatform V3
-- Customer Onboarding Database
--
-- Database: EwpCustomerDb
--
-- Bounded Context:
--     Customer Onboarding
--
-- Ownership:
--     Customer Onboarding Microservice
--
-- IMPORTANT:
--     This database must not be accessed directly by other microservices.
--     Cross-service communication will happen through APIs and Kafka events.
-- ============================================================================

-- ============================================================================
-- Connect to EwpCustomerDb before executing the remaining statements.
-- ============================================================================
--
-- In pgAdmin:
--     Select EwpCustomerDb and open Query Tool.
--
-- In psql:
--     \c EwpCustomerDb
--
-- ============================================================================

-- ============================================================================ 
-- CUSTOMER NUMBER SEQUENCE
-- ============================================================================

CREATE SEQUENCE public.customer_number_seq
    AS BIGINT
    START WITH 100001
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 20;

-- ============================================================================
-- CUSTOMERS
-- ============================================================================
--
-- Aggregate Root:
--     Customer
--
-- Owns the core customer identity and lifecycle within the
-- Customer Onboarding bounded context.
--
-- ============================================================================

CREATE TABLE customers
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY,

    customer_number    VARCHAR(30)  NOT NULL,

    subject_id         UUID         NULL,

    first_name         VARCHAR(100) NOT NULL,
    last_name          VARCHAR(100) NOT NULL,

    email              VARCHAR(254) NOT NULL,
    phone_number       VARCHAR(30)  NOT NULL,

    customer_type      VARCHAR(30)  NOT NULL,
    status             VARCHAR(30)  NOT NULL,

    branch_id          BIGINT       NULL,

    created_at         TIMESTAMPTZ  NOT NULL,
    updated_at         TIMESTAMPTZ  NOT NULL,

    version             BIGINT       NOT NULL DEFAULT 1,

    CONSTRAINT pk_customers
        PRIMARY KEY (id),

    CONSTRAINT uq_customers_customer_number
        UNIQUE (customer_number),

    CONSTRAINT uq_customers_subject_id
        UNIQUE (subject_id),

    CONSTRAINT ck_customers_customer_type
        CHECK
        (
            customer_type IN
            (
                'INDIVIDUAL',
                'BUSINESS'
            )
        ),

    CONSTRAINT ck_customers_status
        CHECK
        (
            status IN
            (
                'PROSPECT',
                'ONBOARDING',
                'ACTIVE',
                'SUSPENDED',
                'CLOSED'
            )
        ),

    CONSTRAINT ck_customers_version
        CHECK (version > 0)
);


-- ============================================================================
-- CUSTOMER ADDRESSES
-- ============================================================================
--
-- A Customer may have multiple addresses.
--
-- The address belongs to the Customer aggregate and therefore contains
-- a foreign key to customers.
--
-- ============================================================================

CREATE TABLE customer_addresses
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY,

    customer_id         BIGINT       NOT NULL,

    address_type        VARCHAR(30)  NOT NULL,

    address_line1      VARCHAR(200) NOT NULL,
    address_line2      VARCHAR(200) NULL,

    city                VARCHAR(100) NOT NULL,
    state               VARCHAR(100) NOT NULL,
    postal_code         VARCHAR(20)  NOT NULL,
    country_code        CHAR(2)      NOT NULL,

    is_primary          BOOLEAN      NOT NULL DEFAULT FALSE,

    created_at          TIMESTAMPTZ  NOT NULL,
    updated_at          TIMESTAMPTZ  NOT NULL,

    CONSTRAINT pk_customer_addresses
        PRIMARY KEY (id),

    CONSTRAINT fk_customer_addresses_customer
        FOREIGN KEY (customer_id)
        REFERENCES customers (id)
        ON DELETE CASCADE,

    CONSTRAINT ck_customer_addresses_address_type
        CHECK
        (
            address_type IN
            (
                'RESIDENTIAL',
                'BUSINESS',
                'MAILING'
            )
        ),

    CONSTRAINT ck_customer_addresses_country_code
        CHECK (length(country_code) = 2)
);


-- ============================================================================
-- ONBOARDING APPLICATIONS
-- ============================================================================
--
-- Aggregate Root:
--     OnboardingApplication
--
-- Represents an application to onboard a Customer.
--
-- This table deliberately contains no KYC, Compliance, Account or Payment
-- information. Those belong to other bounded contexts.
--
-- ============================================================================

CREATE TABLE onboarding_applications
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY,

    application_number  VARCHAR(30)  NOT NULL,

    customer_id         BIGINT       NOT NULL,

    status              VARCHAR(50)  NOT NULL,

    submitted_at       TIMESTAMPTZ  NULL,
    completed_at       TIMESTAMPTZ  NULL,

    created_at         TIMESTAMPTZ  NOT NULL,
    updated_at         TIMESTAMPTZ  NOT NULL,

    version             BIGINT       NOT NULL DEFAULT 1,

    CONSTRAINT pk_onboarding_applications
        PRIMARY KEY (id),

    CONSTRAINT uq_onboarding_applications_application_number
        UNIQUE (application_number),

    CONSTRAINT fk_onboarding_applications_customer
        FOREIGN KEY (customer_id)
        REFERENCES customers (id)
        ON DELETE RESTRICT,

    CONSTRAINT ck_onboarding_applications_status
        CHECK
        (
            status IN
            (
                'DRAFT',
                'SUBMITTED',
                'KYC_IN_PROGRESS',
                'KYC_COMPLETED',
                'COMPLIANCE_IN_PROGRESS',
                'COMPLIANCE_COMPLETED',
                'ACCOUNT_OPENING_IN_PROGRESS',
                'COMPLETED',
                'REJECTED',
                'CANCELLED',
                'COMPENSATING',
                'COMPENSATION_FAILED'
            )
        ),

    CONSTRAINT ck_onboarding_applications_version
        CHECK (version > 0)
);


-- ============================================================================
-- OUTBOX MESSAGES
-- ============================================================================
--
-- Implements the Transactional Outbox pattern.
--
-- Business state and the corresponding event are written within the same
-- database transaction.
--
-- The Outbox Publisher will later publish unpublished records to Kafka.
--
-- ============================================================================

CREATE TABLE outbox_messages
(
    id                  UUID         NOT NULL,

    aggregate_type      VARCHAR(100) NOT NULL,
    aggregate_id        VARCHAR(100) NOT NULL,

    event_type          VARCHAR(200) NOT NULL,

    payload             JSONB        NOT NULL,

    occurred_at         TIMESTAMPTZ  NOT NULL,

    published_at        TIMESTAMPTZ  NULL,

    attempt_count       INTEGER      NOT NULL DEFAULT 0,

    last_attempt_at     TIMESTAMPTZ  NULL,

    last_error          TEXT         NULL,

    CONSTRAINT pk_outbox_messages
        PRIMARY KEY (id),

    CONSTRAINT ck_outbox_messages_attempt_count
        CHECK (attempt_count >= 0)
);


-- ============================================================================
-- INBOX MESSAGES
-- ============================================================================
--
-- Supports idempotent processing of messages received from Kafka.
--
-- A Kafka message may be delivered more than once. The combination of
-- message_id + consumer identifies whether a particular consumer has
-- already processed that message.
--
-- ============================================================================

CREATE TABLE inbox_messages
(
    id                  UUID         NOT NULL,

    message_id          UUID         NOT NULL,

    consumer            VARCHAR(200) NOT NULL,

    received_at         TIMESTAMPTZ  NOT NULL,

    processed_at        TIMESTAMPTZ  NULL,

    CONSTRAINT pk_inbox_messages
        PRIMARY KEY (id),

    CONSTRAINT uq_inbox_messages_message_consumer
        UNIQUE (message_id, consumer)
);


-- ============================================================================
-- INDEXES
-- ============================================================================


-- ----------------------------------------------------------------------------
-- Customers
-- ----------------------------------------------------------------------------

CREATE INDEX ix_customers_status
    ON customers (status);

CREATE INDEX ix_customers_branch_id
    ON customers (branch_id);

CREATE INDEX ix_customers_email
    ON customers (email);


-- ----------------------------------------------------------------------------
-- Customer Addresses
-- ----------------------------------------------------------------------------

CREATE INDEX ix_customer_addresses_customer_id
    ON customer_addresses (customer_id);

CREATE INDEX ix_customer_addresses_customer_address_type
    ON customer_addresses (customer_id, address_type);


-- ----------------------------------------------------------------------------
-- Onboarding Applications
-- ----------------------------------------------------------------------------

CREATE INDEX ix_onboarding_applications_customer_id
    ON onboarding_applications (customer_id);

CREATE INDEX ix_onboarding_applications_status
    ON onboarding_applications (status);

CREATE INDEX ix_onboarding_applications_status_created_at
    ON onboarding_applications (status, created_at);


-- ----------------------------------------------------------------------------
-- Outbox
-- ----------------------------------------------------------------------------
--
-- The Outbox Publisher will normally search for records where
-- published_at IS NULL, ordered by occurred_at.
--
-- ----------------------------------------------------------------------------

-- Unpublished messages are the primary polling workload of the
-- Outbox Publisher. A partial index keeps this index focused on the
-- rows that still need to be published.
CREATE INDEX ix_outbox_messages_unpublished
    ON outbox_messages (occurred_at)
    WHERE published_at IS NULL;

CREATE INDEX ix_outbox_messages_aggregate
    ON outbox_messages (aggregate_type, aggregate_id);


-- ----------------------------------------------------------------------------
-- Inbox
-- ----------------------------------------------------------------------------

CREATE INDEX ix_inbox_messages_message_id
    ON inbox_messages (message_id);


-- ============================================================================
-- END OF EwpCustomerDb
-- ============================================================================