-- ============================================================
-- EwpBssShellDb - Banking Services System Shell Menu Database
-- V3 canonical PostgreSQL schema + seed data
--
-- Purpose:
--   Stores Shell navigation/composition metadata only.
--   Identity, permissions and business data remain owned by
--   EwpIdentityAccessDB and the individual microservice databases.
--
-- Development endpoints:
--   Customer Onboarding -> existing Products application URL
--   Customer KYC        -> existing Orders application URL
--   Accounts            -> reserved
--   Payments            -> reserved
--
-- PostgreSQL naming convention:
--   Tables, columns, constraints and indexes use lowercase snake_case.
--   C# types/properties remain idiomatic PascalCase and are mapped by EF Core.
--
-- NOTE:
--   Menu visibility is NOT the authoritative authorization mechanism.
--   BFF/API authorization remains responsible for RBAC/ABAC/ReBAC.
-- ============================================================

BEGIN;

-- ============================================================
-- Drop existing V2/V3 Shell menu tables.
-- Reverse dependency order.
-- ============================================================

DROP TABLE IF EXISTS menu_items_and_roles;
DROP TABLE IF EXISTS menu_items;
DROP TABLE IF EXISTS management_areas;
DROP TABLE IF EXISTS microservices;

-- ============================================================
-- Table: microservices
-- ============================================================

CREATE TABLE microservices
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    base_url VARCHAR(500) NOT NULL,

    CONSTRAINT uq_microservices_name
        UNIQUE (name),

    CONSTRAINT uq_microservices_base_url
        UNIQUE (base_url)
);

-- ============================================================
-- Table: management_areas
-- ============================================================

CREATE TABLE management_areas
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    description VARCHAR(500) NOT NULL,
    microservice_id BIGINT NOT NULL,

    CONSTRAINT fk_management_areas_microservices
        FOREIGN KEY (microservice_id)
        REFERENCES microservices (id)
        ON DELETE RESTRICT,

    CONSTRAINT uq_management_areas_microservice_name
        UNIQUE (microservice_id, name)
);

-- ============================================================
-- Table: menu_items
-- ============================================================

CREATE TABLE menu_items
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_name VARCHAR(200) NOT NULL,
    url_relative_path VARCHAR(500) NOT NULL,
    icon_name VARCHAR(100) NOT NULL,
    management_area_id BIGINT NOT NULL,

    CONSTRAINT fk_menu_items_management_areas
        FOREIGN KEY (management_area_id)
        REFERENCES management_areas (id)
        ON DELETE CASCADE,

    CONSTRAINT uq_menu_items_management_area_task_name
        UNIQUE (management_area_id, task_name),

    CONSTRAINT ck_menu_items_url_relative_path
        CHECK (url_relative_path LIKE '/%')
);

-- ============================================================
-- Table: menu_items_and_roles
--
-- Role codes deliberately remain strings. The Shell database
-- must not own or duplicate the IdentityAccessDB role catalogue.
-- ============================================================

CREATE TABLE menu_items_and_roles
(
    menu_item_id BIGINT NOT NULL,
    role_short_name VARCHAR(100) NOT NULL,

    CONSTRAINT pk_menu_items_and_roles
        PRIMARY KEY (menu_item_id, role_short_name),

    CONSTRAINT fk_menu_items_and_roles_menu_items
        FOREIGN KEY (menu_item_id)
        REFERENCES menu_items (id)
        ON DELETE CASCADE
);

-- ============================================================
-- Indexes
-- ============================================================

CREATE INDEX ix_management_areas_microservice_id
    ON management_areas (microservice_id);

CREATE INDEX ix_menu_items_management_area_id
    ON menu_items (management_area_id);

CREATE INDEX ix_menu_items_and_roles_role_short_name
    ON menu_items_and_roles (role_short_name);

CREATE INDEX ix_menu_items_and_roles_menu_item_id
    ON menu_items_and_roles (menu_item_id);

-- ============================================================
-- Seed: Microservices
--
-- Existing V2 application URLs are intentionally retained and
-- mapped to their V3 bounded-context responsibilities:
--
--   Products -> Customer Onboarding
--   Orders   -> Customer KYC
--
-- Accounts and Payments use reserved development ports.
-- ============================================================

INSERT INTO microservices (name, base_url)
VALUES
    ('Customer Onboarding', 'https://customer.dev.localhost:44311'),
    ('Customer KYC',        'https://kyc.dev.localhost:33800'),
    ('Accounts',            'https://accounts.dev.localhost:34000'),
    ('Payments',            'https://payments.dev.localhost:35000');

-- ============================================================
-- Seed: Management Areas
-- ============================================================

INSERT INTO management_areas
    (name, description, microservice_id)
VALUES
    (
        'Customer Management',
        'Manage customer profiles and customer information.',
        (SELECT id FROM microservices WHERE name = 'Customer Onboarding')
    ),
    (
        'Onboarding Applications',
        'Create, review and manage customer onboarding applications.',
        (SELECT id FROM microservices WHERE name = 'Customer Onboarding')
    ),
    (
        'Onboarding Workflow',
        'Monitor customer onboarding workflow and saga progress.',
        (SELECT id FROM microservices WHERE name = 'Customer Onboarding')
    ),
    (
        'KYC Cases',
        'Manage customer KYC cases and their lifecycle.',
        (SELECT id FROM microservices WHERE name = 'Customer KYC')
    ),
    (
        'Identity Verification',
        'Review identity verification activities and results.',
        (SELECT id FROM microservices WHERE name = 'Customer KYC')
    ),
    (
        'Document Verification',
        'Review and manage customer document verification.',
        (SELECT id FROM microservices WHERE name = 'Customer KYC')
    ),
    (
        'Compliance',
        'Monitor compliance checks, screening and decisions.',
        (SELECT id FROM microservices WHERE name = 'Customer KYC')
    ),
    (
        'Account Applications',
        'Review and manage account opening applications.',
        (SELECT id FROM microservices WHERE name = 'Accounts')
    ),
    (
        'Accounts',
        'View and manage customer accounts.',
        (SELECT id FROM microservices WHERE name = 'Accounts')
    ),
    (
        'Account Lifecycle',
        'Manage account lifecycle operations.',
        (SELECT id FROM microservices WHERE name = 'Accounts')
    ),
    (
        'Payment Instructions',
        'Create and manage payment instructions.',
        (SELECT id FROM microservices WHERE name = 'Payments')
    ),
    (
        'Beneficiaries',
        'Manage payment beneficiaries.',
        (SELECT id FROM microservices WHERE name = 'Payments')
    ),
    (
        'Payment Processing',
        'Monitor payment processing and payment workflow status.',
        (SELECT id FROM microservices WHERE name = 'Payments')
    );

-- ============================================================
-- Seed: Menu Items
-- ============================================================

-- ------------------------------------------------------------
-- Customer Onboarding
-- ------------------------------------------------------------

INSERT INTO menu_items
    (task_name, url_relative_path, icon_name, management_area_id)
VALUES
    (
        'View Customers',
        '/v1/customers/view-all',
        'fa-users',
        (SELECT id FROM management_areas
         WHERE name = 'Customer Management'
           AND microservice_id =
               (SELECT id FROM microservices
                WHERE name = 'Customer Onboarding'))
    ),
    (
        'View Onboarding Applications',
        '/v1/onboarding/applications/view-all',
        'fa-file-lines',
        (SELECT id FROM management_areas
         WHERE name = 'Onboarding Applications'
           AND microservice_id =
               (SELECT id FROM microservices
                WHERE name = 'Customer Onboarding'))
    ),
    (
        'Onboarding Workflow Monitor',
        '/v1/onboarding/workflow/view-all',
        'fa-diagram-project',
        (SELECT id FROM management_areas
         WHERE name = 'Onboarding Workflow'
           AND microservice_id =
               (SELECT id FROM microservices
                WHERE name = 'Customer Onboarding'))
    );

-- ------------------------------------------------------------
-- Customer KYC
-- ------------------------------------------------------------

INSERT INTO menu_items
    (task_name, url_relative_path, icon_name, management_area_id)
VALUES
    (
        'View KYC Cases',
        '/v1/kyc/cases/view-all',
        'fa-id-card',
        (SELECT id FROM management_areas
         WHERE name = 'KYC Cases'
           AND microservice_id =
               (SELECT id FROM microservices
                WHERE name = 'Customer KYC'))
    ),
    (
        'Identity Verification',
        '/v1/kyc/identity-verification/view-all',
        'fa-user-check',
        (SELECT id FROM management_areas
         WHERE name = 'Identity Verification'
           AND microservice_id =
               (SELECT id FROM microservices
                WHERE name = 'Customer KYC'))
    ),
    (
        'Document Verification',
        '/v1/kyc/documents/view-all',
        'fa-file-circle-check',
        (SELECT id FROM management_areas
         WHERE name = 'Document Verification'
           AND microservice_id =
               (SELECT id FROM microservices
                WHERE name = 'Customer KYC'))
    ),
    (
        'Compliance Monitor',
        '/v1/compliance/view-all',
        'fa-shield-halved',
        (SELECT id FROM management_areas
         WHERE name = 'Compliance'
           AND microservice_id =
               (SELECT id FROM microservices
                WHERE name = 'Customer KYC'))
    );

-- ------------------------------------------------------------
-- Accounts
-- ------------------------------------------------------------

INSERT INTO menu_items
    (task_name, url_relative_path, icon_name, management_area_id)
VALUES
    (
        'View Account Applications',
        '/v1/accounts/applications/view-all',
        'fa-file-circle-plus',
        (SELECT id FROM management_areas
         WHERE name = 'Account Applications'
           AND microservice_id =
               (SELECT id FROM microservices
                WHERE name = 'Accounts'))
    ),
    (
        'View Accounts',
        '/v1/accounts/view-all',
        'fa-building-columns',
        (SELECT id FROM management_areas
         WHERE name = 'Accounts'
           AND microservice_id =
               (SELECT id FROM microservices
                WHERE name = 'Accounts'))
    ),
    (
        'Account Lifecycle',
        '/v1/accounts/lifecycle/view-all',
        'fa-arrows-rotate',
        (SELECT id FROM management_areas
         WHERE name = 'Account Lifecycle'
           AND microservice_id =
               (SELECT id FROM microservices
                WHERE name = 'Accounts'))
    );

-- ------------------------------------------------------------
-- Payments
-- ------------------------------------------------------------

INSERT INTO menu_items
    (task_name, url_relative_path, icon_name, management_area_id)
VALUES
    (
        'View Payments',
        '/v1/payments/view-all',
        'fa-money-bill-transfer',
        (SELECT id FROM management_areas
         WHERE name = 'Payment Instructions'
           AND microservice_id =
               (SELECT id FROM microservices
                WHERE name = 'Payments'))
    ),
    (
        'Manage Beneficiaries',
        '/v1/payments/beneficiaries/view-all',
        'fa-address-book',
        (SELECT id FROM management_areas
         WHERE name = 'Beneficiaries'
           AND microservice_id =
               (SELECT id FROM microservices
                WHERE name = 'Payments'))
    ),
    (
        'Payment Processing Monitor',
        '/v1/payments/processing/view-all',
        'fa-chart-line',
        (SELECT id FROM management_areas
         WHERE name = 'Payment Processing'
           AND microservice_id =
               (SELECT id FROM microservices
                WHERE name = 'Payments'))
    );

-- ============================================================
-- Seed: Menu Item -> Role mappings
--
-- These are navigation visibility rules only.
-- The authoritative RBAC/ABAC/ReBAC decisions remain in the
-- BFF/API layers.
-- ============================================================

-- Customer Management
INSERT INTO menu_items_and_roles (menu_item_id, role_short_name)
SELECT mi.id, r.role_short_name
FROM menu_items mi
CROSS JOIN
(
    VALUES
        ('customer'),
        ('customer_service_agent'),
        ('operations_administrator'),
        ('auditor'),
        ('platform_administrator')
) AS r(role_short_name)
WHERE mi.task_name = 'View Customers';

-- Onboarding Applications
INSERT INTO menu_items_and_roles (menu_item_id, role_short_name)
SELECT mi.id, r.role_short_name
FROM menu_items mi
CROSS JOIN
(
    VALUES
        ('customer'),
        ('customer_service_agent'),
        ('operations_administrator'),
        ('auditor'),
        ('platform_administrator')
) AS r(role_short_name)
WHERE mi.task_name = 'View Onboarding Applications';

-- Onboarding Workflow Monitor
INSERT INTO menu_items_and_roles (menu_item_id, role_short_name)
SELECT mi.id, r.role_short_name
FROM menu_items mi
CROSS JOIN
(
    VALUES
        ('customer_service_agent'),
        ('operations_administrator'),
        ('auditor'),
        ('platform_administrator')
) AS r(role_short_name)
WHERE mi.task_name = 'Onboarding Workflow Monitor';

-- KYC Cases
INSERT INTO menu_items_and_roles (menu_item_id, role_short_name)
SELECT mi.id, r.role_short_name
FROM menu_items mi
CROSS JOIN
(
    VALUES
        ('kyc_officer'),
        ('compliance_officer'),
        ('operations_administrator'),
        ('auditor'),
        ('platform_administrator')
) AS r(role_short_name)
WHERE mi.task_name = 'View KYC Cases';

-- Identity Verification
INSERT INTO menu_items_and_roles (menu_item_id, role_short_name)
SELECT mi.id, r.role_short_name
FROM menu_items mi
CROSS JOIN
(
    VALUES
        ('kyc_officer'),
        ('compliance_officer'),
        ('operations_administrator'),
        ('auditor'),
        ('platform_administrator')
) AS r(role_short_name)
WHERE mi.task_name = 'Identity Verification';

-- Document Verification
INSERT INTO menu_items_and_roles (menu_item_id, role_short_name)
SELECT mi.id, r.role_short_name
FROM menu_items mi
CROSS JOIN
(
    VALUES
        ('kyc_officer'),
        ('compliance_officer'),
        ('operations_administrator'),
        ('auditor'),
        ('platform_administrator')
) AS r(role_short_name)
WHERE mi.task_name = 'Document Verification';

-- Compliance
INSERT INTO menu_items_and_roles (menu_item_id, role_short_name)
SELECT mi.id, r.role_short_name
FROM menu_items mi
CROSS JOIN
(
    VALUES
        ('compliance_officer'),
        ('operations_administrator'),
        ('auditor'),
        ('platform_administrator')
) AS r(role_short_name)
WHERE mi.task_name = 'Compliance Monitor';

-- Account Applications
INSERT INTO menu_items_and_roles (menu_item_id, role_short_name)
SELECT mi.id, r.role_short_name
FROM menu_items mi
CROSS JOIN
(
    VALUES
        ('account_officer'),
        ('operations_administrator'),
        ('auditor'),
        ('platform_administrator')
) AS r(role_short_name)
WHERE mi.task_name = 'View Account Applications';

-- Accounts
INSERT INTO menu_items_and_roles (menu_item_id, role_short_name)
SELECT mi.id, r.role_short_name
FROM menu_items mi
CROSS JOIN
(
    VALUES
        ('customer'),
        ('account_officer'),
        ('operations_administrator'),
        ('auditor'),
        ('platform_administrator')
) AS r(role_short_name)
WHERE mi.task_name = 'View Accounts';

-- Account Lifecycle
INSERT INTO menu_items_and_roles (menu_item_id, role_short_name)
SELECT mi.id, r.role_short_name
FROM menu_items mi
CROSS JOIN
(
    VALUES
        ('account_officer'),
        ('operations_administrator'),
        ('auditor'),
        ('platform_administrator')
) AS r(role_short_name)
WHERE mi.task_name = 'Account Lifecycle';

-- Payments
INSERT INTO menu_items_and_roles (menu_item_id, role_short_name)
SELECT mi.id, r.role_short_name
FROM menu_items mi
CROSS JOIN
(
    VALUES
        ('payments_officer'),
        ('operations_administrator'),
        ('auditor'),
        ('platform_administrator')
) AS r(role_short_name)
WHERE mi.task_name = 'View Payments';

-- Beneficiaries
INSERT INTO menu_items_and_roles (menu_item_id, role_short_name)
SELECT mi.id, r.role_short_name
FROM menu_items mi
CROSS JOIN
(
    VALUES
        ('payments_officer'),
        ('operations_administrator'),
        ('auditor'),
        ('platform_administrator')
) AS r(role_short_name)
WHERE mi.task_name = 'Manage Beneficiaries';

-- Payment Processing
INSERT INTO menu_items_and_roles (menu_item_id, role_short_name)
SELECT mi.id, r.role_short_name
FROM menu_items mi
CROSS JOIN
(
    VALUES
        ('payments_officer'),
        ('operations_administrator'),
        ('auditor'),
        ('platform_administrator')
) AS r(role_short_name)
WHERE mi.task_name = 'Payment Processing Monitor';

-- ============================================================
-- Verification queries
-- ============================================================

-- SELECT * FROM microservices ORDER BY id;
-- SELECT * FROM management_areas ORDER BY microservice_id, id;
-- SELECT * FROM menu_items ORDER BY management_area_id, id;
-- SELECT * FROM menu_items_and_roles ORDER BY menu_item_id, role_short_name;

COMMIT;
