-- ============================================================
-- EwpBssShellDb - Banking Services System Shell Menu Database
-- V3 canonical PostgreSQL schema + seed data
--
-- Purpose:
--   Stores Shell navigation/composition metadata only.
--   Identity, permissions and business data remain owned by
--   EwpIdentityAccessDB and the individual microservice databases.
--
-- Development endpoints:
--   Customer Onboarding -> existing Products application URL
--   Customer KYC        -> existing Orders application URL
--   Accounts            -> reserved
--   Payments            -> reserved
--
-- NOTE:
--   Menu visibility is NOT the authoritative authorization mechanism.
--   BFF/API authorization remains responsible for RBAC/ABAC/ReBAC.
-- ============================================================

BEGIN;

-- ============================================================
-- Drop existing V2/V3 Shell menu tables.
-- Reverse dependency order.
-- ============================================================

DROP TABLE IF EXISTS "MenuItemsAndRoles";
DROP TABLE IF EXISTS "MenuItems";
DROP TABLE IF EXISTS "ManagementAreas";
DROP TABLE IF EXISTS "Microservices";

-- ============================================================
-- Table: Microservices
-- ============================================================

CREATE TABLE "Microservices"
(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name" VARCHAR(150) NOT NULL,
    "BaseURL" VARCHAR(500) NOT NULL,

    CONSTRAINT "UQ_Microservices_Name"
        UNIQUE ("Name"),

    CONSTRAINT "UQ_Microservices_BaseURL"
        UNIQUE ("BaseURL")
);

-- ============================================================
-- Table: ManagementAreas
-- ============================================================

CREATE TABLE "ManagementAreas"
(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name" VARCHAR(150) NOT NULL,
    "Description" VARCHAR(500) NOT NULL,
    "MicroserviceID" BIGINT NOT NULL,

    CONSTRAINT "FK_ManagementAreas_Microservices"
        FOREIGN KEY ("MicroserviceID")
        REFERENCES "Microservices" ("ID")
        ON DELETE RESTRICT,

    CONSTRAINT "UQ_ManagementAreas_Microservice_Name"
        UNIQUE ("MicroserviceID", "Name")
);

-- ============================================================
-- Table: MenuItems
-- ============================================================

CREATE TABLE "MenuItems"
(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "TaskName" VARCHAR(200) NOT NULL,
    "UrlRelativePath" VARCHAR(500) NOT NULL,
    "IconName" VARCHAR(100) NOT NULL,
    "ManagementAreaID" BIGINT NOT NULL,

    CONSTRAINT "FK_MenuItems_ManagementAreas"
        FOREIGN KEY ("ManagementAreaID")
        REFERENCES "ManagementAreas" ("ID")
        ON DELETE CASCADE,

    CONSTRAINT "UQ_MenuItems_ManagementArea_TaskName"
        UNIQUE ("ManagementAreaID", "TaskName"),

    CONSTRAINT "CK_MenuItems_UrlRelativePath"
        CHECK ("UrlRelativePath" LIKE '/%')
);

-- ============================================================
-- Table: MenuItemsAndRoles
--
-- Role codes deliberately remain strings. The Shell database
-- must not own or duplicate the IdentityAccessDB role catalogue.
-- ============================================================

CREATE TABLE "MenuItemsAndRoles"
(
    "MenuItemID" BIGINT NOT NULL,
    "RoleShortName" VARCHAR(100) NOT NULL,

    CONSTRAINT "PK_MenuItemsAndRoles"
        PRIMARY KEY ("MenuItemID", "RoleShortName"),

    CONSTRAINT "FK_MenuItemsAndRoles_MenuItems"
        FOREIGN KEY ("MenuItemID")
        REFERENCES "MenuItems" ("ID")
        ON DELETE CASCADE
);

-- ============================================================
-- Indexes
-- ============================================================

CREATE INDEX "IX_ManagementAreas_MicroserviceID"
    ON "ManagementAreas" ("MicroserviceID");

CREATE INDEX "IX_MenuItems_ManagementAreaID"
    ON "MenuItems" ("ManagementAreaID");

CREATE INDEX "IX_MenuItemsAndRoles_RoleShortName"
    ON "MenuItemsAndRoles" ("RoleShortName");

CREATE INDEX "IX_MenuItemsAndRoles_MenuItemID"
    ON "MenuItemsAndRoles" ("MenuItemID");

-- ============================================================
-- Seed: Microservices
--
-- Existing V2 application URLs are intentionally retained and
-- mapped to their V3 bounded-context responsibilities:
--
--   Products -> Customer Onboarding
--   Orders   -> Customer KYC
--
-- Accounts and Payments use reserved development ports.
-- ============================================================

INSERT INTO "Microservices" ("Name", "BaseURL")
VALUES
    ('Customer Onboarding', 'https://customer.dev.localhost:44311'),
    ('Customer KYC',        'https://kyc.dev.localhost:33800'),
    ('Accounts',            'https://accounts.dev.localhost:34000'),
    ('Payments',            'https://payments.dev.localhost:35000');

-- ============================================================
-- Seed: Management Areas
-- ============================================================

INSERT INTO "ManagementAreas"
    ("Name", "Description", "MicroserviceID")
VALUES
    (
        'Customer Management',
        'Manage customer profiles and customer information.',
        (SELECT "ID" FROM "Microservices" WHERE "Name" = 'Customer Onboarding')
    ),
    (
        'Onboarding Applications',
        'Create, review and manage customer onboarding applications.',
        (SELECT "ID" FROM "Microservices" WHERE "Name" = 'Customer Onboarding')
    ),
    (
        'Onboarding Workflow',
        'Monitor customer onboarding workflow and saga progress.',
        (SELECT "ID" FROM "Microservices" WHERE "Name" = 'Customer Onboarding')
    ),
    (
        'KYC Cases',
        'Manage customer KYC cases and their lifecycle.',
        (SELECT "ID" FROM "Microservices" WHERE "Name" = 'Customer KYC')
    ),
    (
        'Identity Verification',
        'Review identity verification activities and results.',
        (SELECT "ID" FROM "Microservices" WHERE "Name" = 'Customer KYC')
    ),
    (
        'Document Verification',
        'Review and manage customer document verification.',
        (SELECT "ID" FROM "Microservices" WHERE "Name" = 'Customer KYC')
    ),
    (
        'Compliance',
        'Monitor compliance checks, screening and decisions.',
        (SELECT "ID" FROM "Microservices" WHERE "Name" = 'Customer KYC')
    ),
    (
        'Account Applications',
        'Review and manage account opening applications.',
        (SELECT "ID" FROM "Microservices" WHERE "Name" = 'Accounts')
    ),
    (
        'Accounts',
        'View and manage customer accounts.',
        (SELECT "ID" FROM "Microservices" WHERE "Name" = 'Accounts')
    ),
    (
        'Account Lifecycle',
        'Manage account lifecycle operations.',
        (SELECT "ID" FROM "Microservices" WHERE "Name" = 'Accounts')
    ),
    (
        'Payment Instructions',
        'Create and manage payment instructions.',
        (SELECT "ID" FROM "Microservices" WHERE "Name" = 'Payments')
    ),
    (
        'Beneficiaries',
        'Manage payment beneficiaries.',
        (SELECT "ID" FROM "Microservices" WHERE "Name" = 'Payments')
    ),
    (
        'Payment Processing',
        'Monitor payment processing and payment workflow status.',
        (SELECT "ID" FROM "Microservices" WHERE "Name" = 'Payments')
    );

-- ============================================================
-- Seed: Menu Items
-- ============================================================

-- ------------------------------------------------------------
-- Customer Onboarding
-- ------------------------------------------------------------

INSERT INTO "MenuItems"
    ("TaskName", "UrlRelativePath", "IconName", "ManagementAreaID")
VALUES
    (
        'View Customers',
        '/v1/customers/view-all',
        'fa-users',
        (SELECT "ID" FROM "ManagementAreas"
         WHERE "Name" = 'Customer Management'
           AND "MicroserviceID" =
               (SELECT "ID" FROM "Microservices"
                WHERE "Name" = 'Customer Onboarding'))
    ),
    (
        'View Onboarding Applications',
        '/v1/onboarding/applications/view-all',
        'fa-file-lines',
        (SELECT "ID" FROM "ManagementAreas"
         WHERE "Name" = 'Onboarding Applications'
           AND "MicroserviceID" =
               (SELECT "ID" FROM "Microservices"
                WHERE "Name" = 'Customer Onboarding'))
    ),
    (
        'Onboarding Workflow Monitor',
        '/v1/onboarding/workflow/view-all',
        'fa-diagram-project',
        (SELECT "ID" FROM "ManagementAreas"
         WHERE "Name" = 'Onboarding Workflow'
           AND "MicroserviceID" =
               (SELECT "ID" FROM "Microservices"
                WHERE "Name" = 'Customer Onboarding'))
    );

-- ------------------------------------------------------------
-- Customer KYC
-- ------------------------------------------------------------

INSERT INTO "MenuItems"
    ("TaskName", "UrlRelativePath", "IconName", "ManagementAreaID")
VALUES
    (
        'View KYC Cases',
        '/v1/kyc/cases/view-all',
        'fa-id-card',
        (SELECT "ID" FROM "ManagementAreas"
         WHERE "Name" = 'KYC Cases'
           AND "MicroserviceID" =
               (SELECT "ID" FROM "Microservices"
                WHERE "Name" = 'Customer KYC'))
    ),
    (
        'Identity Verification',
        '/v1/kyc/identity-verification/view-all',
        'fa-user-check',
        (SELECT "ID" FROM "ManagementAreas"
         WHERE "Name" = 'Identity Verification'
           AND "MicroserviceID" =
               (SELECT "ID" FROM "Microservices"
                WHERE "Name" = 'Customer KYC'))
    ),
    (
        'Document Verification',
        '/v1/kyc/documents/view-all',
        'fa-file-circle-check',
        (SELECT "ID" FROM "ManagementAreas"
         WHERE "Name" = 'Document Verification'
           AND "MicroserviceID" =
               (SELECT "ID" FROM "Microservices"
                WHERE "Name" = 'Customer KYC'))
    ),
    (
        'Compliance Monitor',
        '/v1/compliance/view-all',
        'fa-shield-halved',
        (SELECT "ID" FROM "ManagementAreas"
         WHERE "Name" = 'Compliance'
           AND "MicroserviceID" =
               (SELECT "ID" FROM "Microservices"
                WHERE "Name" = 'Customer KYC'))
    );

-- ------------------------------------------------------------
-- Accounts
-- ------------------------------------------------------------

INSERT INTO "MenuItems"
    ("TaskName", "UrlRelativePath", "IconName", "ManagementAreaID")
VALUES
    (
        'View Account Applications',
        '/v1/accounts/applications/view-all',
        'fa-file-circle-plus',
        (SELECT "ID" FROM "ManagementAreas"
         WHERE "Name" = 'Account Applications'
           AND "MicroserviceID" =
               (SELECT "ID" FROM "Microservices"
                WHERE "Name" = 'Accounts'))
    ),
    (
        'View Accounts',
        '/v1/accounts/view-all',
        'fa-building-columns',
        (SELECT "ID" FROM "ManagementAreas"
         WHERE "Name" = 'Accounts'
           AND "MicroserviceID" =
               (SELECT "ID" FROM "Microservices"
                WHERE "Name" = 'Accounts'))
    ),
    (
        'Account Lifecycle',
        '/v1/accounts/lifecycle/view-all',
        'fa-arrows-rotate',
        (SELECT "ID" FROM "ManagementAreas"
         WHERE "Name" = 'Account Lifecycle'
           AND "MicroserviceID" =
               (SELECT "ID" FROM "Microservices"
                WHERE "Name" = 'Accounts'))
    );

-- ------------------------------------------------------------
-- Payments
-- ------------------------------------------------------------

INSERT INTO "MenuItems"
    ("TaskName", "UrlRelativePath", "IconName", "ManagementAreaID")
VALUES
    (
        'View Payments',
        '/v1/payments/view-all',
        'fa-money-bill-transfer',
        (SELECT "ID" FROM "ManagementAreas"
         WHERE "Name" = 'Payment Instructions'
           AND "MicroserviceID" =
               (SELECT "ID" FROM "Microservices"
                WHERE "Name" = 'Payments'))
    ),
    (
        'Manage Beneficiaries',
        '/v1/payments/beneficiaries/view-all',
        'fa-address-book',
        (SELECT "ID" FROM "ManagementAreas"
         WHERE "Name" = 'Beneficiaries'
           AND "MicroserviceID" =
               (SELECT "ID" FROM "Microservices"
                WHERE "Name" = 'Payments'))
    ),
    (
        'Payment Processing Monitor',
        '/v1/payments/processing/view-all',
        'fa-chart-line',
        (SELECT "ID" FROM "ManagementAreas"
         WHERE "Name" = 'Payment Processing'
           AND "MicroserviceID" =
               (SELECT "ID" FROM "Microservices"
                WHERE "Name" = 'Payments'))
    );

-- ============================================================
-- Seed: Menu Item -> Role mappings
--
-- These are navigation visibility rules only.
-- The authoritative RBAC/ABAC/ReBAC decisions remain in the
-- BFF/API layers.
-- ============================================================

-- Customer Management
INSERT INTO "MenuItemsAndRoles" ("MenuItemID", "RoleShortName")
SELECT mi."ID", r."Role"
FROM "MenuItems" mi
CROSS JOIN
(
    VALUES
        ('customer'),
        ('customer_service_agent'),
        ('operations_administrator'),
        ('auditor'),
        ('platform_administrator')
) AS r("Role")
WHERE mi."TaskName" = 'View Customers';

-- Onboarding Applications
INSERT INTO "MenuItemsAndRoles" ("MenuItemID", "RoleShortName")
SELECT mi."ID", r."Role"
FROM "MenuItems" mi
CROSS JOIN
(
    VALUES
        ('customer'),
        ('customer_service_agent'),
        ('operations_administrator'),
        ('auditor'),
        ('platform_administrator')
) AS r("Role")
WHERE mi."TaskName" = 'View Onboarding Applications';

-- Onboarding Workflow Monitor
INSERT INTO "MenuItemsAndRoles" ("MenuItemID", "RoleShortName")
SELECT mi."ID", r."Role"
FROM "MenuItems" mi
CROSS JOIN
(
    VALUES
        ('customer_service_agent'),
        ('operations_administrator'),
        ('auditor'),
        ('platform_administrator')
) AS r("Role")
WHERE mi."TaskName" = 'Onboarding Workflow Monitor';

-- KYC Cases
INSERT INTO "MenuItemsAndRoles" ("MenuItemID", "RoleShortName")
SELECT mi."ID", r."Role"
FROM "MenuItems" mi
CROSS JOIN
(
    VALUES
        ('kyc_officer'),
        ('compliance_officer'),
        ('operations_administrator'),
        ('auditor'),
        ('platform_administrator')
) AS r("Role")
WHERE mi."TaskName" = 'View KYC Cases';

-- Identity Verification
INSERT INTO "MenuItemsAndRoles" ("MenuItemID", "RoleShortName")
SELECT mi."ID", r."Role"
FROM "MenuItems" mi
CROSS JOIN
(
    VALUES
        ('kyc_officer'),
        ('compliance_officer'),
        ('operations_administrator'),
        ('auditor'),
        ('platform_administrator')
) AS r("Role")
WHERE mi."TaskName" = 'Identity Verification';

-- Document Verification
INSERT INTO "MenuItemsAndRoles" ("MenuItemID", "RoleShortName")
SELECT mi."ID", r."Role"
FROM "MenuItems" mi
CROSS JOIN
(
    VALUES
        ('kyc_officer'),
        ('compliance_officer'),
        ('operations_administrator'),
        ('auditor'),
        ('platform_administrator')
) AS r("Role")
WHERE mi."TaskName" = 'Document Verification';

-- Compliance
INSERT INTO "MenuItemsAndRoles" ("MenuItemID", "RoleShortName")
SELECT mi."ID", r."Role"
FROM "MenuItems" mi
CROSS JOIN
(
    VALUES
        ('compliance_officer'),
        ('operations_administrator'),
        ('auditor'),
        ('platform_administrator')
) AS r("Role")
WHERE mi."TaskName" = 'Compliance Monitor';

-- Account Applications
INSERT INTO "MenuItemsAndRoles" ("MenuItemID", "RoleShortName")
SELECT mi."ID", r."Role"
FROM "MenuItems" mi
CROSS JOIN
(
    VALUES
        ('account_officer'),
        ('operations_administrator'),
        ('auditor'),
        ('platform_administrator')
) AS r("Role")
WHERE mi."TaskName" = 'View Account Applications';

-- Accounts
INSERT INTO "MenuItemsAndRoles" ("MenuItemID", "RoleShortName")
SELECT mi."ID", r."Role"
FROM "MenuItems" mi
CROSS JOIN
(
    VALUES
        ('customer'),
        ('account_officer'),
        ('operations_administrator'),
        ('auditor'),
        ('platform_administrator')
) AS r("Role")
WHERE mi."TaskName" = 'View Accounts';

-- Account Lifecycle
INSERT INTO "MenuItemsAndRoles" ("MenuItemID", "RoleShortName")
SELECT mi."ID", r."Role"
FROM "MenuItems" mi
CROSS JOIN
(
    VALUES
        ('account_officer'),
        ('operations_administrator'),
        ('auditor'),
        ('platform_administrator')
) AS r("Role")
WHERE mi."TaskName" = 'Account Lifecycle';

-- Payments
INSERT INTO "MenuItemsAndRoles" ("MenuItemID", "RoleShortName")
SELECT mi."ID", r."Role"
FROM "MenuItems" mi
CROSS JOIN
(
    VALUES
        ('payments_officer'),
        ('operations_administrator'),
        ('auditor'),
        ('platform_administrator')
) AS r("Role")
WHERE mi."TaskName" = 'View Payments';

-- Beneficiaries
INSERT INTO "MenuItemsAndRoles" ("MenuItemID", "RoleShortName")
SELECT mi."ID", r."Role"
FROM "MenuItems" mi
CROSS JOIN
(
    VALUES
        ('payments_officer'),
        ('operations_administrator'),
        ('auditor'),
        ('platform_administrator')
) AS r("Role")
WHERE mi."TaskName" = 'Manage Beneficiaries';

-- Payment Processing
INSERT INTO "MenuItemsAndRoles" ("MenuItemID", "RoleShortName")
SELECT mi."ID", r."Role"
FROM "MenuItems" mi
CROSS JOIN
(
    VALUES
        ('payments_officer'),
        ('operations_administrator'),
        ('auditor'),
        ('platform_administrator')
) AS r("Role")
WHERE mi."TaskName" = 'Payment Processing Monitor';

-- ============================================================
-- Verification queries
-- ============================================================

-- SELECT * FROM "Microservices" ORDER BY "ID";
-- SELECT * FROM "ManagementAreas" ORDER BY "MicroserviceID", "ID";
-- SELECT * FROM "MenuItems" ORDER BY "ManagementAreaID", "ID";
-- SELECT * FROM "MenuItemsAndRoles" ORDER BY "MenuItemID", "RoleShortName";

COMMIT;
