<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>EnterpriseWebPlatform.BSS.AsyncWorkflows.Contracts</RootNamespace>
    <AssemblyName>EnterpriseWebPlatform.BSS.AsyncWorkflows.Contracts</AssemblyName>
  </PropertyGroup>

</Project>