-- =============================================================================
-- EwpIdentityAccessDb - upgrade (step 6c): two-step sign-in (TOTP - Google Authenticator)
-- =============================================================================
-- For an EXISTING database whose users and roles must be kept. Adds the two MFA tables
-- (empty: everyone enrols at their next sign-in once "Mfa:Enabled" is true). Re-running it
-- drops them again - every enrolment is lost. A fresh database gets the same tables from
-- IdentityAccessDb.sql.
--   psql -h localhost -U postgres -d EwpIdentityAccessDb -v ON_ERROR_STOP=1 -f Upgrade-6c-Mfa.sql
-- ewp_idp's default privileges (ps\database\Apply-EwpServiceDbUsers.ps1) cover new tables;
-- the grant below makes it explicit.
-- =============================================================================

BEGIN;

DROP TABLE IF EXISTS user_mfa_recovery_codes;
DROP TABLE IF EXISTS user_mfa;

-- =========================================================
-- 8b. TWO-STEP SIGN-IN (TOTP - Google Authenticator)
-- =========================================================
-- One authenticator per user. The secret is stored ONLY encrypted with the IDP's Data
-- Protection key ring (schema identity_server), so a database reader cannot generate codes;
-- last_used_time_step stops a code being replayed. Recovery codes: SHA-256 hashes only.
-- Used only while "Mfa:Enabled" is true (IDP appsettings); enrolment happens at sign-in.

CREATE TABLE user_mfa (
    user_id BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    secret_protected TEXT NOT NULL,
    enrolled_at TIMESTAMPTZ NOT NULL,
    last_used_time_step BIGINT NOT NULL
);

CREATE TABLE user_mfa_recovery_codes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    code_hash CHAR(64) NOT NULL,
    used_at TIMESTAMPTZ NULL
);

CREATE INDEX ix_user_mfa_recovery_codes_user_id ON user_mfa_recovery_codes (user_id);

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'ewp_idp') THEN
        GRANT SELECT, INSERT, UPDATE, DELETE ON user_mfa, user_mfa_recovery_codes TO ewp_idp;
        GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO ewp_idp;
    END IF;
END $$;

COMMIT;

SELECT 'user_mfa and user_mfa_recovery_codes ready' AS result;